#!/usr/bin/env python

def fib(n):
    
    z = [1, 1]
    
    if n <= 1:
        return z[n]
    
    
    for i in range(2, n + 1):
        z.append(z[- 1] + z[- 2])
    return z[n]


        
n = raw_input("> ")
n = int(n)
    
print fib(n)


