#!/usr/bin/env python3


"""This Script
Described in details
"""

import argparse
import logging
import sys

# Configure the command-line arguments
params = argparse.ArgumentParser(description = __doc__, formatter_class = argparse.RawDescriptionHelpFormatter)

params.add_argument('--version', action = 'version', version = '%(prog)s 0.1')

params.add_argument('-l',action = 'store_true', dest = 'lines',help='Show the amount of lines')

params.add_argument('-c', action = 'store_true', dest = 'chars', help = 'Shows the amount of characters')

# Parse the command line arguments
args = params.parse_args()


try: 
    words = sys.stdin.read()                        #Input wird in words gespeichert 
    a = 0                                           #Festlegen einer Variablen
    
    
    if args.lines:                                  #Prüfung ob Option -l angegeben wurde
        for i in words.splitlines():                #Auffteilung nach Zeilenumbruechen 
        
            a += 1                                  #wird a um 1 erhoeht
        print(f"Der Text hat: {a} Zeilen.")         
        
    elif args.chars:                                #Prüfen ob Option -c angegeben wurde
        
        list(words)                                 #Input in eine Liste schreiben; Aufteilen jedes einzelnen Zeichens
        
        for i in words:                             
            if i == " " or i == "\n" or i == "\t":  #Prüfen ob Leerzeichen, Zeilenumbrueche oder Einrueckungen vorhanden sind
                a += 0                              #Wenn "Ja" wird a nicht erhoeht
                
            else:
                a += 1                              #Wenn "Sonst" wird a um 1 erhoeht
        
        print(f"Der Text hat: {a} Charaktere.")     
    
    else:
        
        for i in words.split():                     #Aufteilung nach Leerzeilen

            a += 1
        print(f"Der Text hat: {a} Woerter.")    
    
except Exception as exc:
    print(str(exc) + '!')
    exit(1)
    
   
exit(0) 
